//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.20 at 02:41:11 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "assignment.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.eur.spreadsheettest.xml;
