//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.18 at 10:13:24 PM CEST 
//


package nl.eur.spreadsheettest.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for testcaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="testcaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="input" type="{assignment.xsd}inputType" maxOccurs="unbounded"/>
 *         &lt;element name="output" type="{assignment.xsd}outputType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sheetName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="eps" type="{http://www.w3.org/2001/XMLSchema}double" default="10e-8" />
 *       &lt;attribute name="randomCombinations" type="{http://www.w3.org/2001/XMLSchema}int" default="256" />
 *       &lt;attribute name="randomDraws" type="{http://www.w3.org/2001/XMLSchema}int" default="256" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testcaseType", propOrder = {
    "description",
    "input",
    "output"
})
public class TestcaseType {

    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected List<InputType> input;
    @XmlElement(required = true)
    protected List<OutputType> output;
    @XmlAttribute(name = "sheetName")
    protected String sheetName;
    @XmlAttribute(name = "eps")
    protected Double eps;
    @XmlAttribute(name = "randomCombinations")
    protected Integer randomCombinations;
    @XmlAttribute(name = "randomDraws")
    protected Integer randomDraws;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the input property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the input property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InputType }
     * 
     * 
     */
    public List<InputType> getInput() {
        if (input == null) {
            input = new ArrayList<InputType>();
        }
        return this.input;
    }

    /**
     * Gets the value of the output property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the output property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OutputType }
     * 
     * 
     */
    public List<OutputType> getOutput() {
        if (output == null) {
            output = new ArrayList<OutputType>();
        }
        return this.output;
    }

    /**
     * Gets the value of the sheetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSheetName() {
        return sheetName;
    }

    /**
     * Sets the value of the sheetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSheetName(String value) {
        this.sheetName = value;
    }

    /**
     * Gets the value of the eps property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getEps() {
        if (eps == null) {
            return  1.0E-7D;
        } else {
            return eps;
        }
    }

    /**
     * Sets the value of the eps property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setEps(Double value) {
        this.eps = value;
    }

    /**
     * Gets the value of the randomCombinations property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getRandomCombinations() {
        if (randomCombinations == null) {
            return  256;
        } else {
            return randomCombinations;
        }
    }

    /**
     * Sets the value of the randomCombinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRandomCombinations(Integer value) {
        this.randomCombinations = value;
    }

    /**
     * Gets the value of the randomDraws property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getRandomDraws() {
        if (randomDraws == null) {
            return  256;
        } else {
            return randomDraws;
        }
    }

    /**
     * Sets the value of the randomDraws property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRandomDraws(Integer value) {
        this.randomDraws = value;
    }

}
